name: quizapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.4.4
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  image_picker: ^1.1.2
  logger: ^2.5.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
